---
# ==============================================================
# Handlers: acciones reactivas para database
# ==============================================================

- name: restart postgres container
  ansible.builtin.shell: |
    docker restart {{ container_name }}
  args:
    executable: /bin/bash
  changed_when: false
