---
docker_user: "admin"
docker_pat: "{{ lookup('env', 'HARBOR_ADMIN_PASSWORD') }}"
harbor_registry: "harbor.local"
app_image: "harbor.local/picantito/infraestructure-as-code:app-1.0.0"
app_container_name: "myapp"
worker_container_name: "myapp-worker"

# URLs de servicios externos
database_url: "postgresql://piero:piero@10.30.0.1:5432/sgi"
redis_url: "redis://:infra@10.30.0.2:6379"
rabbitmq_url: "amqp://sgi_user:sgi_pass@10.20.0.2:5672"
email_user: "stockcloud.soporte@gmail.com"
email_pass: "ktte cwnu eojo eaxt"
node_env: "production"
session_secret: "infra"

# Directorio donde vivir√° docker-compose de la API
docker_compose_dir: "/opt/docker/api"

# NFS
nfs_client_ip: "10.10.0.3"
