---
# ==============================================================
# Role: database
# Vars: Configuraci√≥n del contenedor PostgreSQL
# ==============================================================

docker_user: "admin"
docker_pat: "{{ lookup('env', 'HARBOR_ADMIN_PASSWORD') }}"
harbor_registry: "harbor.local"
image_name: "harbor.local/picantito/infraestructure-as-code:postgres-1.0.0"
container_name: "mypostgres"

postgres_user: "piero"
postgres_password: "piero"
postgres_db: "sgi"
postgres_data_dir: "/opt/postgres_data"   # Ruta para los datos de PostgreSQL
