---
# ======================================================
# Role: rabbitmq
# Default variables
# ======================================================

# Imagen y contenedor
rabbitmq_image: "rabbitmq:3-management"
rabbitmq_container_name: "rabbitmq_sgi"

# Credenciales
rabbitmq_user: "sgi_user"
rabbitmq_pass: "sgi_pass"

# Puertos
rabbitmq_amqp_port: 5672
rabbitmq_http_port: 15672

# Directorio de despliegue
rabbitmq_dir: /root/rabbitmq
